# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "workspace-cluster-tfstate"
    encrypt      = true
    key          = "foundation/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
